# Generated by Django 6.0.5 on 2026-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
