# Generated by Django 6.0.5 on 2026-05-13 07:43

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_quill.fields.QuillField(),
        ),
    ]
