# Generated by Django 6.0.5 on 2026-05-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_member_only',
            field=models.BooleanField(default=False, help_text='Only followers can read this article'),
        ),
    ]
