# Generated by Django 6.0.5 on 2026-05-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_article', 'New Article'), ('comment', 'Comment'), ('reply', 'Reply to Comment'), ('bookmark', 'Article Liked'), ('follow', 'New Follower')], max_length=20),
        ),
    ]
